In [1]:
import pandas as pd

In [2]:
####CLINVAR IN CLINVAR

In [9]:
df_clinvar_in_clinvar = pd.read_csv("df_final_clinvar_in_clinvar_(2).txt", sep="\t", header=0)
df_clinvar_in_clinvar = df_clinvar_in_clinvar.drop_duplicates()
df_clinvar_in_clinvar

,Gene(s),position,initial_aa,final_aa,Transmembrane_Regions_new,Pfam_code,ID,ID_correct,pos_align,Database
0,GJB4,137.0,F,L,"[['21', '40'], ['74', '94'], ['131', '151'], [...",PF00029,['CXB4_HUMAN'],CXB4_HUMAN,[500],ClinVar
1,GJB2,142.0,F,L,"[['21', '40'], ['74', '94'], ['136', '156'], [...",PF00029,"['CXB2_HUMAN', 'A0A2R4SEG2_HUMAN', 'A8DU55_HUM...",CXB2_HUMAN,[500],ClinVar
2,GJB1,141.0,F,L,"[['23', '45'], ['76', '95'], ['131', '153'], [...",PF00029,"['CXB1_HUMAN', 'A0A2R8YD01_HUMAN', 'C9JWU8_HUM...",CXB1_HUMAN,[500],ClinVar
3,GJB3,37.0,V,E,"[['21', '40'], ['76', '98'], ['127', '149'], [...",PF00029,['CXB3_HUMAN'],CXB3_HUMAN,[153],ClinVar
4,GJB6,37.0,V,E,"[['23', '45'], ['76', '98'], ['132', '154'], [...",PF00029,"['CXB6_HUMAN', 'A0A024RDS4_HUMAN', 'A0A2R8Y4J9...",CXB6_HUMAN,[153],ClinVar
...,...,...,...,...,...,...,...,...,...,...
277,CACNA1F,1297.0,R,TER,"[['93', '111'], ['130', '149'], ['162', '180']...",PF00520,"['CAC1F_HUMAN', 'H7C549_HUMAN']",CAC1F_HUMAN,[868],ClinVar
278,CACNA1A,1344.0,L,P,"[['99', '117'], ['136', '155'], ['168', '185']...",PF00520,"['CAC1A_HUMAN', 'A0A087WW63_HUMAN', 'A0A1B0GTG...",CAC1A_HUMAN,[860],ClinVar
279,KCNQ2,200.0,L,P,"[['92', '112'], ['123', '143'], ['167', '187']...",PF00520,"['KCNQ2_HUMAN', 'A0A0D9SEV1_HUMAN', 'A0A0D9SF1...",KCNQ2_HUMAN,[860],ClinVar
280,RYR1,4851.0,L,P,"[['4560', '4580'], ['4642', '4662'], ['4781', ...",PF00520,"['RYR1_HUMAN', 'G9I593_HUMAN', 'L8E9F3_HUMAN',...",RYR1_HUMAN,[1237],ClinVar
281,KCNQ2,245.0,L,P,"[['92', '112'], ['123', '143'], ['167', '187']...",PF00520,"['KCNQ2_HUMAN', 'A0A0D9SEV1_HUMAN', 'A0A0D9SF1...",KCNQ2_HUMAN,[1237],ClinVar

In [4]:
dups_color_clinvar_in_clinvar = df_clinvar_in_clinvar.pivot_table(columns=['initial_aa', 'final_aa', 'Pfam_code', 'pos_align'], aggfunc='size')
dups_color_clinvar_in_clinvar.to_csv('PAIRS_CLINVAR IN CLINVAR', header=True, index=False, sep='\t', mode='w')
dups_color_clinvar_in_clinvar

initial_aa  final_aa  Pfam_code  pos_align
A           E         PF00520    [1982]       2
                                 [682]        2
            P         PF00520    [1982]       2
            T         PF00520    [1996]       2
            V         PF00029    [155]        3
                                             ..
W           TER       PF00520    [630]        2
                                 [985]        2
                      PF07690    [610]        2
Y           TER       PF00029    [516]        2
                      PF01770    [199]        2
Length: 126, dtype: int64

In [17]:
df_clinvar_in_clinvar_SUM = pd.read_csv("PAIRS_CLINVAR IN CLINVAR", sep="\t", header=0)
df_clinvar_in_clinvar_SUM = df_clinvar_in_clinvar_SUM.rename(columns={"0":"Values"})
df_clinvar_in_clinvar_SUM

     Values
0         2
1         2
2         2
3         2
4         3
..      ...
121       2
122       2
123       2
124       2
125       2

[126 rows x 1 columns]

In [18]:
df_clinvar_in_clinvar_SUM.pivot_table(columns=['Values'], aggfunc='size')

Values
2    100
3     23
4      2
5      1
dtype: int64

In [ ]:
#### Clinvar in GNOMAD

In [14]:
df_clinvar_in_gnomad = pd.read_csv("df_clinvar_in_gnomad_without_homologous_nonPatho.txt", sep="\t", header=0)

df_clinvar_in_gnomad

,Gene(s),position,initial_aa,final_aa,Transmembrane_Regions_new,Pfam_code,ID,ID_correct,pos_align,Database
0,SCN1A,216.0,R,H,"[['129', '147'], ['155', '175'], ['190', '207'...",PF00520,"['SCN1A_HUMAN', 'A0A1B0GU68_HUMAN', 'A0A1B0GUN...",SCN1A_HUMAN,[863],GnomAD
1,SCN1A,216.0,R,C,"[['129', '147'], ['155', '175'], ['190', '207'...",PF00520,"['SCN1A_HUMAN', 'A0A1B0GU68_HUMAN', 'A0A1B0GUN...",SCN1A_HUMAN,[863],GnomAD
2,DHCR7,429.0,P,R,"[['40', '60'], ['154', '174'], ['177', '197'],...",PF01222,"['DHCR7_HUMAN', 'A0A024R5F7_HUMAN', 'A0A0S2Z3N...",DHCR7_HUMAN,[1993],GnomAD
3,KCNH5,330.0,R,Q,"[['218', '238'], ['244', '264'], ['292', '312'...",PF00520,"['KCNH5_HUMAN', 'Q86XI1_HUMAN']",KCNH5_HUMAN,[897],GnomAD
4,SCN1A,986.0,L,F,"[['129', '147'], ['155', '175'], ['190', '207'...",PF00520,"['SCN1A_HUMAN', 'A0A1B0GU68_HUMAN', 'A0A1B0GUN...",SCN1A_HUMAN,[1984],ClinVar
5,SCN1A,157.0,V,I,"[['129', '147'], ['155', '175'], ['190', '207'...",PF00520,"['SCN1A_HUMAN', 'A0A1B0GU68_HUMAN', 'A0A1B0GUN...",SCN1A_HUMAN,[402],ClinVar
6,SCN1A,146.0,M,T,"[['129', '147'], ['155', '175'], ['190', '207'...",PF00520,"['SCN1A_HUMAN', 'A0A1B0GU68_HUMAN', 'A0A1B0GUN...",SCN1A_HUMAN,[253],ClinVar
7,SCN1A,416.0,N,S,"[['129', '147'], ['155', '175'], ['190', '207'...",PF00520,"['SCN1A_HUMAN', 'A0A1B0GU68_HUMAN', 'A0A1B0GUN...",SCN1A_HUMAN,[1982],ClinVar
8,SCN1A,402.0,F,I,"[['129', '147'], ['155', '175'], ['190', '207'...",PF00520,"['SCN1A_HUMAN', 'A0A1B0GU68_HUMAN', 'A0A1B0GUN...",SCN1A_HUMAN,[1896],ClinVar
9,SCN1A,263.0,L,V,"[['129', '147'], ['155', '175'], ['190', '207'...",PF00520,"['SCN1A_HUMAN', 'A0A1B0GU68_HUMAN', 'A0A1B0GUN...",SCN1A_HUMAN,[1259],ClinVar
10,SCN1A,253.0,L,P,"[['129', '147'], ['155', '175'], ['190', '207'...",PF00520,"['SCN1A_HUMAN', 'A0A1B0GU68_HUMAN', 'A0A1B0GUN...",SCN1A_HUMAN,[1178],ClinVar
11,SCN1A,250.0,V,I,"[['129', '147'], ['155', '175'], ['190', '207'...",PF00520,"['SCN1A_HUMAN', 'A0A1B0GU68_HUMAN', 'A0A1B0GUN...",SCN1A_HUMAN,[1156],ClinVar
12,SCN1A,228.0,S,P,"[['129', '147'], ['155', '175'], ['190', '207'...",PF00520,"['SCN1A_HUMAN', 'A0A1B0GU68_HUMAN', 'A0A1B0GUN...",SCN1A_HUMAN,[957],ClinVar
13,SCN1A,225.0,K,N,"[['129', '147'], ['155', '175'], ['190', '207'...",PF00520,"['SCN1A_HUMAN', 'A0A1B0GU68_HUMAN', 'A0A1B0GUN...",SCN1A_HUMAN,[925],ClinVar
14,SCN1A,221.0,L,P,"[['129', '147'], ['155', '175'], ['190', '207'...",PF00520,"['SCN1A_HUMAN', 'A0A1B0GU68_HUMAN', 'A0A1B0GUN...",SCN1A_HUMAN,[890],ClinVar
15,SCN1A,219.0,R,S,"[['129', '147'], ['155', '175'], ['190', '207'...",PF00520,"['SCN1A_HUMAN', 'A0A1B0GU68_HUMAN', 'A0A1B0GUN...",SCN1A_HUMAN,[880],ClinVar
16,SCN1A,218.0,F,L,"[['129', '147'], ['155', '175'], ['190', '207'...",PF00520,"['SCN1A_HUMAN', 'A0A1B0GU68_HUMAN', 'A0A1B0GUN...",SCN1A_HUMAN,[872],ClinVar
17,SCN1A,194.0,D,Y,"[['129', '147'], ['155', '175'], ['190', '207'...",PF00520,"['SCN1A_HUMAN', 'A0A1B0GU68_HUMAN', 'A0A1B0GUN...",SCN1A_HUMAN,[646],ClinVar
18,SCN1A,194.0,D,N,"[['129', '147'], ['155', '175'], ['190', '207'...",PF00520,"['SCN1A_HUMAN', 'A0A1B0GU68_HUMAN', 'A0A1B0GUN...",SCN1A_HUMAN,[646],ClinVar
19,SCN1A,175.0,A,T,"[['129', '147'], ['155', '175'], ['190', '207'...",PF00520,"['SCN1A_HUMAN', 'A0A1B0GU68_HUMAN', 'A0A1B0GUN...",SCN1A_HUMAN,[488],ClinVar
20,SCN1A,162.0,T,I,"[['129', '147'], ['155', '175'], ['190', '207'...",PF00520,"['SCN1A_HUMAN', 'A0A1B0GU68_HUMAN', 'A0A1B0GUN...",SCN1A_HUMAN,[417],ClinVar
21,SCN1A,145.0,M,V,"[['129', '147'], ['155', '175'], ['190', '207'...",PF00520,"['SCN1A_HUMAN', 'A0A1B0GU68_HUMAN', 'A0A1B0GUN...",SCN1A_HUMAN,[251],ClinVar
22,SCN1A,141.0,N,K,"[['129', '147'], ['155', '175'], ['190', '207'...",PF00520,"['SCN1A_HUMAN', 'A0A1B0GU68_HUMAN', 'A0A1B0GUN...",SCN1A_HUMAN,[237],ClinVar
23,CELSR3,2575.0,H,R,"[['2541', '2561'], ['2573', '2593'], ['2602', ...",PF00002,"['CELR3_HUMAN', 'L0R6E8_HUMAN']",CELR3_HUMAN,[355],GnomAD
24,SLC25A20,229.0,P,L,"[['13', '31'], ['74', '93'], ['113', '131'], [...",PF00153,"['MCAT_HUMAN', 'C9JPE1_HUMAN', 'F8WEF6_HUMAN']",MCAT_HUMAN,[193],GnomAD
25,SLC26A4,94.0,T,I,"[['88', '108'], ['110', '130'], ['136', '156']...",PF00916,"['S26A4_HUMAN', 'A0A2R8Y4W7_HUMAN', 'C9JQG1_HU...",S26A4_HUMAN,[156],ClinVar
26,SLC26A4,112.0,P,S,"[['88', '108'], ['110', '130'], ['136', '156']...",PF00916,"['S26A4_HUMAN', 'A0A2R8Y4W7_HUMAN', 'C9JQG1_HU...",S26A4_HUMAN,[248],ClinVar
27,SLC26A4,138.0,V,L,"[['88', '108'], ['110', '130'], ['136', '156']...",PF00916,"['S26A4_HUMAN', 'A0A2R8Y4W7_HUMAN', 'C9JQG1_HU...",S26A4_HUMAN,[405],ClinVar
28,SLC26A4,139.0,G,V,"[['88', '108'], ['110', '130'], ['136', '156']...",PF00916,"['S26A4_HUMAN', 'A0A2R8Y4W7_HUMAN', 'C9JQG1_HU...",S26A4_HUMAN,[416],ClinVar
29,CLCN7,512.0,G,R,"[['127', '159'], ['174', '197'], ['223', '241'...",PF00654,"['CLCN7_HUMAN', 'H0Y2M6_HUMAN', 'H3BNG8_HUMAN'...",CLCN7_HUMAN,[1521],GnomAD
30,SCN1A,224.0,L,W,"[['129', '147'], ['155', '175'], ['190', '207'...",PF00520,"['SCN1A_HUMAN', 'A0A1B0GU68_HUMAN', 'A0A1B0GUN...",SCN1A_HUMAN,[919],GnomAD
31,GJB2,206.0,N,S,"[['21', '40'], ['74', '94'], ['136', '156'], [...",PF00029,"['CXB2_HUMAN', 'A0A2R4SEG2_HUMAN', 'A8DU55_HUM...",CXB2_HUMAN,[616],ClinVar
32,GJB2,195.0,M,V,"[['21', '40'], ['74', '94'], ['136', '156'], [...",PF00029,"['CXB2_HUMAN', 'A0A2R4SEG2_HUMAN', 'A8DU55_HUM...",CXB2_HUMAN,[596],ClinVar
33,GJB2,147.0,E,K,"[['21', '40'], ['74', '94'], ['136', '156'], [...",PF00029,"['CXB2_HUMAN', 'A0A2R4SEG2_HUMAN', 'A8DU55_HUM...",CXB2_HUMAN,[506],ClinVar
34,GJB2,143.0,R,Q,"[['21', '40'], ['74', '94'], ['136', '156'], [...",PF00029,"['CXB2_HUMAN', 'A0A2R4SEG2_HUMAN', 'A8DU55_HUM...",CXB2_HUMAN,[501],ClinVar
35,GJB2,89.0,L,P,"[['21', '40'], ['74', '94'], ['136', '156'], [...",PF00029,"['CXB2_HUMAN', 'A0A2R4SEG2_HUMAN', 'A8DU55_HUM...",CXB2_HUMAN,[236],ClinVar
36,GJB2,84.0,V,L,"[['21', '40'], ['74', '94'], ['136', '156'], [...",PF00029,"['CXB2_HUMAN', 'A0A2R4SEG2_HUMAN', 'A8DU55_HUM...",CXB2_HUMAN,[230],ClinVar
37,GJB2,82.0,I,M,"[['21', '40'], ['74', '94'], ['136', '156'], [...",PF00029,"['CXB2_HUMAN', 'A0A2R4SEG2_HUMAN', 'A8DU55_HUM...",CXB2_HUMAN,[228],ClinVar
38,GJB2,78.0,A,T,"[['21', '40'], ['74', '94'], ['136', '156'], [...",PF00029,"['CXB2_HUMAN', 'A0A2R4SEG2_HUMAN', 'A8DU55_HUM...",CXB2_HUMAN,[217],ClinVar
39,GJB2,77.0,W,R,"[['21', '40'], ['74', '94'], ['136', '156'], [...",PF00029,"['CXB2_HUMAN', 'A0A2R4SEG2_HUMAN', 'A8DU55_HUM...",CXB2_HUMAN,[216],ClinVar
40,GJB2,32.0,R,L,"[['21', '40'], ['74', '94'], ['136', '156'], [...",PF00029,"['CXB2_HUMAN', 'A0A2R4SEG2_HUMAN', 'A8DU55_HUM...",CXB2_HUMAN,[148],ClinVar
41,GJB2,32.0,R,H,"[['21', '40'], ['74', '94'], ['136', '156'], [...",PF00029,"['CXB2_HUMAN', 'A0A2R4SEG2_HUMAN', 'A8DU55_HUM...",CXB2_HUMAN,[148],ClinVar
42,GJB2,32.0,R,C,"[['21', '40'], ['74', '94'], ['136', '156'], [...",PF00029,"['CXB2_HUMAN', 'A0A2R4SEG2_HUMAN', 'A8DU55_HUM...",CXB2_HUMAN,[148],ClinVar
43,KCNH5,327.0,R,H,"[['218', '238'], ['244', '264'], ['292', '312'...",PF00520,"['KCNH5_HUMAN', 'Q86XI1_HUMAN']",KCNH5_HUMAN,[880],ClinVar
44,PSEN1,142.0,V,I,"[['83', '103'], ['133', '153'], ['167', '189']...",PF01080,"['PSN1_HUMAN', 'A0A024R6A3_HUMAN', 'A0A0S2Z484...",PSN1_HUMAN,[312],ClinVar
45,GJB2,91.0,V,M,"[['21', '40'], ['74', '94'], ['136', '156'], [...",PF00029,"['CXB2_HUMAN', 'A0A2R4SEG2_HUMAN', 'A8DU55_HUM...",CXB2_HUMAN,[239],GnomAD

In [18]:
dups_color_clinvar_in_gnomad = df_clinvar_in_gnomad.pivot_table(columns=['initial_aa', 'final_aa', 'Pfam_code', 'pos_align'], aggfunc='size')
dups_color_clinvar_in_gnomad.to_csv('PAIRS_CLINVAR IN GNOMAD', header=True, index=False, sep='\t', mode='w')
dups_color_clinvar_in_gnomad

initial_aa  final_aa  Pfam_code  pos_align
A           T         PF00029    [217]        1
                      PF00520    [488]        1
D           N         PF00520    [646]        1
            Y         PF00520    [646]        1
E           K         PF00029    [506]        1
F           I         PF00520    [1896]       1
            L         PF00520    [872]        1
G           R         PF00654    [1521]       1
            V         PF00916    [416]        1
H           R         PF00002    [355]        1
I           M         PF00029    [228]        1
K           N         PF00520    [925]        1
L           F         PF00520    [1984]       1
            P         PF00029    [236]        1
                      PF00520    [1178]       1
                                 [890]        1
            V         PF00520    [1259]       1
            W         PF00520    [919]        1
M           T         PF00520    [253]        1
            V         PF00029    [596]        1
                      PF00520    [251]        1
N           K         PF00520    [237]        1
            S         PF00029    [616]        1
                      PF00520    [1982]       1
P           L         PF00153    [193]        1
            R         PF01222    [1993]       1
            S         PF00916    [248]        1
R           C         PF00029    [148]        1
                      PF00520    [863]        1
            H         PF00029    [148]        1
                      PF00520    [863]        1
                                 [880]        1
            L         PF00029    [148]        1
            Q         PF00029    [501]        1
                      PF00520    [897]        1
            S         PF00520    [880]        1
S           P         PF00520    [957]        1
T           I         PF00520    [417]        1
                      PF00916    [156]        1
V           I         PF00520    [1156]       1
                                 [402]        1
                      PF01080    [312]        1
            L         PF00029    [230]        1
                      PF00916    [405]        1
            M         PF00029    [239]        1
W           R         PF00029    [216]        1
dtype: int64

In [16]:
df_clinvar_in_gnomad_SUM = pd.read_csv("PAIRS_CLINVAR IN GNOMAD", sep="\t", header=0)
df_clinvar_in_gnomad_SUM = df_clinvar_in_gnomad_SUM.rename(columns={"0":"Values"})
df_clinvar_in_gnomad_SUM

    Values
0        1
1        1
2        1
3        1
4        1
5        1
6        1
7        1
8        1
9        1
10       1
11       1
12       1
13       1
14       1
15       1
16       1
17       1
18       1
19       1
20       1
21       1
22       1
23       1
24       1
25       1
26       1
27       1
28       1
29       1
30       1
31       1
32       1
33       1
34       1
35       1
36       1
37       1
38       1
39       1
40       1
41       1
42       1
43       1
44       1
45       1

In [17]:
df_clinvar_in_gnomad_SUM.pivot_table(columns=['Values'], aggfunc='size')

Values
1    46
dtype: int64

In [ ]:
# gNOMAD IN gnomad

In [21]:
df_gnomad_in_gnomad = pd.read_csv("df_final_gnomad_in_gnomad_nonPatho.txt", sep="\t", header=0)
df_gnomad_in_gnomad = df_gnomad_in_gnomad.drop_duplicates()
df_gnomad_in_gnomad

,Gene(s),position,initial_aa,final_aa,Transmembrane_Regions_new,Pfam_code,ID,ID_correct,pos_align,Database
0,SLC45A1,132.0,L,L,"[['127', '147'], ['157', '177'], ['189', '209'...",PF07690,"['S45A1_HUMAN', 'A0A2H2EQP0_HUMAN']",S45A1_HUMAN,[193],GnomAD
1,FLVCR1,112.0,L,L,"[['108', '128'], ['148', '168'], ['175', '195'...",PF07690,"['FLVC1_HUMAN', 'H7C3Z2_HUMAN']",FLVC1_HUMAN,[193],GnomAD
2,SLC45A1,165.0,A,A,"[['127', '147'], ['157', '177'], ['189', '209'...",PF07690,"['S45A1_HUMAN', 'A0A2H2EQP0_HUMAN']",S45A1_HUMAN,[671],GnomAD
3,SLC16A1,67.0,A,A,"[['16', '36'], ['60', '80'], ['87', '107'], ['...",PF07690,"['MOT1_HUMAN', 'A0A024R0H1_HUMAN', 'Q5T8R3_HUM...",MOT1_HUMAN,[671],GnomAD
4,SLC45A1,166.0,L,L,"[['127', '147'], ['157', '177'], ['189', '209'...",PF07690,"['S45A1_HUMAN', 'A0A2H2EQP0_HUMAN']",S45A1_HUMAN,[686],GnomAD
...,...,...,...,...,...,...,...,...,...,...
4429,SLC16A2,206.0,G,G,"[['97', '117'], ['144', '164'], ['172', '192']...",PF07690,"['MOT8_HUMAN', 'A0A1B0GVB4_HUMAN', 'K7ELT4_HUM...",MOT8_HUMAN,[1157],GnomAD
4430,KCNQ2,131.0,V,V,"[['92', '112'], ['123', '143'], ['167', '187']...",PF00520,"['KCNQ2_HUMAN', 'A0A0D9SEV1_HUMAN', 'A0A0D9SF1...",KCNQ2_HUMAN,[412],GnomAD
4431,CACNA1I,677.0,V,V,"[['79', '99'], ['121', '141'], ['149', '168'],...",PF00520,['CAC1I_HUMAN'],CAC1I_HUMAN,[412],GnomAD
4432,CACNA1I,1630.0,F,F,"[['79', '99'], ['121', '141'], ['149', '168'],...",PF00520,['CAC1I_HUMAN'],CAC1I_HUMAN,[1225],GnomAD
4433,CACNA1F,1338.0,F,F,"[['93', '111'], ['130', '149'], ['162', '180']...",PF00520,"['CAC1F_HUMAN', 'H7C549_HUMAN']",CAC1F_HUMAN,[1225],GnomAD

In [22]:
dups_color_gnomad_in_gnomad = df_gnomad_in_gnomad.pivot_table(columns=['initial_aa', 'final_aa', 'Pfam_code', 'pos_align'], aggfunc='size')
dups_color_gnomad_in_gnomad.to_csv('PAIRS_GNOMAD IN GNOMAD', header=True, index=False, sep='\t', mode='w')
dups_color_gnomad_in_gnomad

initial_aa  final_aa  Pfam_code  pos_align
A           A         PF00002    [1229]       2
                                 [1632]       2
                                 [181]        4
                                 [198]        2
                                 [364]        2
                                             ..
Y           Y         PF03151    [1546]       2
                      PF05653    [1889]       3
                                 [567]        2
                      PF07690    [1894]       2
                                 [2410]       2
Length: 1722, dtype: int64

In [23]:
df_gnomad_in_gnomad_SUM = pd.read_csv("PAIRS_GNOMAD IN GNOMAD", sep="\t", header=0)
df_gnomad_in_gnomad_SUM = df_gnomad_in_gnomad_SUM.rename(columns={"0":"Values"})
df_gnomad_in_gnomad_SUM

      Values
0          2
1          2
2          4
3          2
4          2
...      ...
1717       2
1718       3
1719       2
1720       2
1721       2

[1722 rows x 1 columns]

In [24]:
df_gnomad_in_gnomad_SUM.pivot_table(columns=['Values'], aggfunc='size')

Values
2     1243
3      260
4      102
5       54
6       24
7       12
8        7
9        6
10       9
11       1
12       2
13       1
14       1
dtype: int64