In [28]:
import pandas as pd

In [29]:
ClinVar = pd.read_csv("File2_tojoinwith_GnomAD(ClinVar).txt", sep=" ", header=0)
ClinVar

     Gene(s) Prot change Molecular Consequence Clinical Significance Database
0       DVL1      S578fs            Frameshift            Pathogenic  ClinVar
1       DVL1      T565fs            Frameshift            Pathogenic  ClinVar
2       DVL1      S562fs            Frameshift            Pathogenic  ClinVar
3       DVL1      S542fs            Frameshift            Pathogenic  ClinVar
4       DVL1      S564fs            Frameshift            Pathogenic  ClinVar
...      ...         ...                   ...                   ...      ...
3939   OPHN1         NaN           Splicesites     Likely pathogenic  ClinVar
3940   OPHN1         NaN           Splicesites     Likely pathogenic  ClinVar
3941    DLG3         NaN           Splicesites     Likely pathogenic  ClinVar
3942    DLG3         NaN           Splicesites     Likely pathogenic  ClinVar
3943   NLGN3         NaN           Splicesites     Likely pathogenic  ClinVar

[3944 rows x 5 columns]

In [47]:
countsClinVar =ClinVar.value_counts(["Gene(s)", "Molecular Consequence", "Database"]).reset_index(name="Counts")
countsClinVar.rename(columns={'Molecular Consequence': 'Molecular Consequence/VEP Annotation'}, inplace=True)
countsClinVar

                 Gene(s) Molecular Consequence/VEP Annotation Database  Counts
0                  CDKL5                           Frameshift  ClinVar     275
1                  SCN2A                             Missense  ClinVar     234
2                   CDH1                           Frameshift  ClinVar     224
3                SYNGAP1                           Frameshift  ClinVar     200
4                 STXBP1                           Frameshift  ClinVar     123
..                   ...                                  ...      ...     ...
304                 EPS8                          Splicesites  ClinVar       1
305                ERBB4                             Nonsense  ClinVar       1
306        FLRT3|MACROD2                             Missense  ClinVar       1
307  PRKAR1B|PRKAR1B-AS1                             Missense  ClinVar       1
308               HOMER2                             Missense  ClinVar       1

[309 rows x 4 columns]

In [31]:
GnomAD = pd.read_csv("File2_tojoinwith_ClinVar(GnomAD).txt", sep=" ", header=0)
GnomAD

,Gene(s),HGVS Consequence,VEP Annotation,Clinical Significance,Database
0,SEMA3F,c.-48-13T>A,intron_variant,Non pathogenic,GnomAD
1,SEMA3F,c.-47T>G,splice_region_variant,Non pathogenic,GnomAD
2,SEMA3F,c.-36T>A,5_prime_UTR_variant,Non pathogenic,GnomAD
3,SEMA3F,c.-34G>A,5_prime_UTR_variant,Non pathogenic,GnomAD
4,SEMA3F,c.-31C>T,5_prime_UTR_variant,Non pathogenic,GnomAD
...,...,...,...,...,...
295861,DYNLL2,c.*47G>A,3_prime_UTR_variant,Non pathogenic,GnomAD
295862,DYNLL2,c.*49C>T,3_prime_UTR_variant,Non pathogenic,GnomAD
295863,DYNLL2,c.*50G>A,3_prime_UTR_variant,Non pathogenic,GnomAD
295864,DYNLL2,c.*52C>T,3_prime_UTR_variant,Non pathogenic,GnomAD
295865,DYNLL2,c.*71C>T,3_prime_UTR_variant,Non pathogenic,GnomAD

In [48]:
countsGnomAD = GnomAD.value_counts(["Gene(s)", "VEP Annotation", "Database"]).reset_index(name="Counts")
countsGnomAD.rename(columns={'VEP Annotation': 'Molecular Consequence/VEP Annotation'}, inplace=True)
countsGnomAD

      Gene(s) Molecular Consequence/VEP Annotation Database  Counts
0        PCLO                     missense_variant   GnomAD    2989
1         BSN                     missense_variant   GnomAD    2247
2       AKAP9                     missense_variant   GnomAD    2030
3       PTPRD                       intron_variant   GnomAD    1545
4       SCRIB                       intron_variant   GnomAD    1434
...       ...                                  ...      ...     ...
3530  GUCY1B1                    inframe_insertion   GnomAD       1
3531     PAK2                   frameshift_variant   GnomAD       1
3532  GUCY1A1                            stop_lost   GnomAD       1
3533  GUCY1A1                           start_lost   GnomAD       1
3534  PPP2R2A                 splice_donor_variant   GnomAD       1

[3535 rows x 4 columns]

In [49]:
result = countsClinVar.append(countsGnomAD, ignore_index=True)
result

      Gene(s) Molecular Consequence/VEP Annotation Database  Counts
0       CDKL5                           Frameshift  ClinVar     275
1       SCN2A                             Missense  ClinVar     234
2        CDH1                           Frameshift  ClinVar     224
3     SYNGAP1                           Frameshift  ClinVar     200
4      STXBP1                           Frameshift  ClinVar     123
...       ...                                  ...      ...     ...
3839  GUCY1B1                    inframe_insertion   GnomAD       1
3840     PAK2                   frameshift_variant   GnomAD       1
3841  GUCY1A1                            stop_lost   GnomAD       1
3842  GUCY1A1                           start_lost   GnomAD       1
3843  PPP2R2A                 splice_donor_variant   GnomAD       1

[3844 rows x 4 columns]

In [53]:
result = result.sort_values(by=['Gene(s)'])
result

      Gene(s) Molecular Consequence/VEP Annotation Database  Counts
2987  ABHD17A                     inframe_deletion   GnomAD       2
2982  ABHD17A                 splice_donor_variant   GnomAD       2
1709  ABHD17A                splice_region_variant   GnomAD      20
3523  ABHD17A                            stop_lost   GnomAD       1
2544  ABHD17A                   frameshift_variant   GnomAD       5
...       ...                                  ...      ...     ...
2730    YWHAZ                          stop_gained   GnomAD       3
1244    YWHAZ                   synonymous_variant   GnomAD      56
2779    YWHAZ                     inframe_deletion   GnomAD       3
2916    YWHAZ              splice_acceptor_variant   GnomAD       2
792     YWHAZ                       intron_variant   GnomAD     204

[3844 rows x 4 columns]

In [55]:
result.index = range(len(result))
result

      Gene(s) Molecular Consequence/VEP Annotation Database  Counts
0     ABHD17A                     inframe_deletion   GnomAD       2
1     ABHD17A                 splice_donor_variant   GnomAD       2
2     ABHD17A                splice_region_variant   GnomAD      20
3     ABHD17A                            stop_lost   GnomAD       1
4     ABHD17A                   frameshift_variant   GnomAD       5
...       ...                                  ...      ...     ...
3839    YWHAZ                          stop_gained   GnomAD       3
3840    YWHAZ                   synonymous_variant   GnomAD      56
3841    YWHAZ                     inframe_deletion   GnomAD       3
3842    YWHAZ              splice_acceptor_variant   GnomAD       2
3843    YWHAZ                       intron_variant   GnomAD     204

[3844 rows x 4 columns]

In [56]:
result.to_csv('File1(Counts).txt', header=True, index=None, sep=' ', mode='a')