# Import libraries

In [1]:
import pandas as pd
import numpy as np

In [2]:
# General function to open files
def open_df(file):
    df = pd.read_csv(file, delimiter = "\t")
    return(df)

# Pathogenic

# Frameshift

In [3]:
df_fs_p = open_df('clinvar_result_frameshift.txt')
df_fs_p

,Name,Gene(s),Protein change,Condition(s),Clinical significance (Last reviewed),Review status,Accession,GRCh37Chromosome,GRCh37Location,GRCh38Chromosome,GRCh38Location,VariationID,AlleleID(s),dbSNP ID,Canonical SPDI,Unnamed: 15
0,NM_001330311.2(DVL1):c.1731del (p.Ser578fs),DVL1,"S578fs, S553fs","Robinow syndrome, autosomal dominant 2|not pro...","Likely pathogenic(Last reviewed: Jul 29, 2020)","criteria provided, single submitter",VCV000504195,1,1271879,1,1336499,504195,495052,rs1553172962,NC_000001.11:1336498:CCC:CC,NaN
1,NM_001330311.2(DVL1):c.1694_1706del (p.Thr565fs),DVL1,"T565fs, T540fs",not provided,"Likely pathogenic(Last reviewed: Mar 23, 2018)","criteria provided, single submitter",VCV000524041,1,1273365 - 1273377,1,1337985 - 1337997,524041,514413,rs1553173356,NC_000001.11:1337984:TGCTGACTCCCGGTGCTG:TGCTG,NaN
2,NM_001330311.2(DVL1):c.1683_1698del (p.Ser562fs),DVL1,"S562fs, S537fs","Robinow syndrome, autosomal dominant 2","Likely pathogenic(Last reviewed: Jun 1, 2017)","criteria provided, single submitter",VCV000488048,1,1273373 - 1273388,1,1337993 - 1338008,488048,481060,rs1553173368,NC_000001.11:1337992:CCCGGTGCTGCCGCTGCC:CC,NaN
3,NM_001330311.2(DVL1):c.1698del (p.Ser567fs),DVL1,"S542fs, S567fs","Robinow syndrome, autosomal dominant 2","Likely pathogenic(Last reviewed: Jun 1, 2017)","criteria provided, single submitter",VCV000488046,1,1273373,1,1337993,488046,481061,rs1553173367,NC_000001.11:1337992:CCC:CC,NaN
4,NM_001330311.2(DVL1):c.1687_1691dup (p.Ser564fs),DVL1,"S564fs, S539fs","Robinow syndrome, autosomal dominant 2","Likely pathogenic(Last reviewed: Jun 1, 2017)","criteria provided, single submitter",VCV000488045,1,1273379 - 1273380,1,1337999 - 1338000,488045,481062,rs1553173372,NC_000001.11:1337999:CTGCC:CTGCCCTGCC,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
874,NM_002578.5(PAK3):c.490_491insGGAG (p.Pro164fs),PAK3,"P164fs, P185fs, P179fs, P200fs",not provided,"Pathogenic(Last reviewed: Feb 1, 2019)","criteria provided, single submitter",VCV000870778,X,110406164 - 110406165,X,111162936 - 111162937,870778,860768,rs2094208830,NC_000023.11:111162936::GGAG,NaN
875,NM_001448.3(GPC4):c.1518_1521dup (p.Pro508fs),GPC4,P508fs,Keipert syndrome,"Pathogenic(Last reviewed: Feb 1, 2019)",no assertion criteria provided,VCV000626360,X,132437044 - 132437045,X,133303016 - 133303017,626360,614692,rs1569339879,NC_000023.11:133303016:GCAC:GCACGCAC,NaN
876,NM_001448.3(GPC4):c.742del (p.Leu248fs),GPC4,L248fs,Keipert syndrome,"Pathogenic(Last reviewed: Feb 1, 2019)",no assertion criteria provided,VCV000626361,X,132445421,X,133311393,626361,614693,rs1569341521,NC_000023.11:133311392:GGG:GG,NaN
877,NM_001448.3(GPC4):c.701dup (p.Val235fs),GPC4,V235fs,Keipert syndrome,"Pathogenic(Last reviewed: Jun 14, 2019)",no assertion criteria provided,VCV000547176,X,132458182 - 132458183,X,133324154 - 133324155,547176,537664,rs1556025980,NC_000023.11:133324154:TT:TTT,NaN
878,NM_001448.3(GPC4):c.316del (p.Asp106fs),GPC4,D106fs,Keipert syndrome,"Pathogenic(Last reviewed: Jun 14, 2019)",no assertion criteria provided,VCV000547178,X,132473214,X,133339186,547178,537665,rs1556028269,NC_000023.11:133339185:C:,NaN

In [4]:
# Select the Gene(s) and Protein change columns to convert it into an easly understandable dataframe
df2_fs_p = df_fs_p[["Gene(s)", "Protein change"]]
df2_fs_p

    Gene(s)                  Protein change
0      DVL1                  S578fs, S553fs
1      DVL1                  T565fs, T540fs
2      DVL1                  S562fs, S537fs
3      DVL1                  S542fs, S567fs
4      DVL1                  S564fs, S539fs
..      ...                             ...
874    PAK3  P164fs, P185fs, P179fs, P200fs
875    GPC4                          P508fs
876    GPC4                          L248fs
877    GPC4                          V235fs
878    GPC4                          D106fs

[879 rows x 2 columns]

In [5]:
# Get the 1st Prot change and separate it into 3 new columns
df2_fs_p['Prot change'] = df2_fs_p['Protein change'].str.split(',').str[0]
df2_fs_p = df2_fs_p.drop(['Protein change'], axis=1)
df2_fs_p[['firstcol', 'secondcol', 'thirdcol']] = df2_fs_p['Prot change'].str.extract('([A-Za-z]+)(\d+\.?\d*)([A-Za-z]*)', expand = True)
df2_fs_p

C:\Users\sergi\AppData\Local\Temp/ipykernel_15016/60221442.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_fs_p['Prot change'] = df2_fs_p['Protein change'].str.split(',').str[0]

    Gene(s) Prot change firstcol secondcol thirdcol
0      DVL1      S578fs        S       578       fs
1      DVL1      T565fs        T       565       fs
2      DVL1      S562fs        S       562       fs
3      DVL1      S542fs        S       542       fs
4      DVL1      S564fs        S       564       fs
..      ...         ...      ...       ...      ...
874    PAK3      P164fs        P       164       fs
875    GPC4      P508fs        P       508       fs
876    GPC4      L248fs        L       248       fs
877    GPC4      V235fs        V       235       fs
878    GPC4      D106fs        D       106       fs

[879 rows x 5 columns]

In [6]:
# Add the type of Protein change
df2_fs_p["Molecular Consequence"] = 'Frameshift'
df2_fs_p

    Gene(s) Prot change firstcol secondcol thirdcol Molecular Consequence
0      DVL1      S578fs        S       578       fs            Frameshift
1      DVL1      T565fs        T       565       fs            Frameshift
2      DVL1      S562fs        S       562       fs            Frameshift
3      DVL1      S542fs        S       542       fs            Frameshift
4      DVL1      S564fs        S       564       fs            Frameshift
..      ...         ...      ...       ...      ...                   ...
874    PAK3      P164fs        P       164       fs            Frameshift
875    GPC4      P508fs        P       508       fs            Frameshift
876    GPC4      L248fs        L       248       fs            Frameshift
877    GPC4      V235fs        V       235       fs            Frameshift
878    GPC4      D106fs        D       106       fs            Frameshift

[879 rows x 6 columns]

# Missense

In [7]:
df_ms_p = open_df('likely_ms.txt')
df_ms_p

,Name,Gene(s),Protein change,Condition(s),Clinical significance (Last reviewed),Review status,Accession,GRCh37Chromosome,GRCh37Location,GRCh38Chromosome,GRCh38Location,VariationID,AlleleID(s),dbSNP ID,Canonical SPDI,Unnamed: 15
0,NM_017449.5(EPHB2):c.2356G>A (p.Gly786Arg),EPHB2,"G786R, G787R, G728R",Neoplasm of the large intestine,"Likely pathogenic(Last reviewed: May 13, 2016)",no assertion criteria provided,VCV000376739,1,23235518,1,22909025,376739,363618,rs138551214,NC_000001.11:22909024:G:A,NaN
1,NM_003285.3(TNR):c.1594G>A (p.Asp532Asn),TNR,"D199N, D532N",Non-progressive neurodevelopmental disorder wi...,"Likely pathogenic(Last reviewed: Jul 25, 2019)","criteria provided, single submitter",VCV000691957,1,175355351,1,175386215,691957,679703,rs892080402,NC_000001.11:175386214:C:T,NaN
2,NM_003285.3(TNR):c.1189G>A (p.Ala397Thr),TNR,"A397T, A64T",Non-progressive neurodevelopmental disorder wi...,"Likely pathogenic(Last reviewed: Jul 25, 2019)","criteria provided, single submitter",VCV000691958,1,175365731,1,175396595,691958,679704,rs750577544,NC_000001.11:175396594:C:T,NaN
3,NM_003128.3(SPTBN1):c.811G>A (p.Val271Met),SPTBN1,"V258M, V271M",Neurodevelopmental disorder,"Likely pathogenic(Last reviewed: Jun 17, 2021)","criteria provided, single submitter",VCV001321938,2,54848584,2,54621447,1321938,1312256,NaN,NC_000002.12:54621446:G:A,NaN
4,NM_139343.3(BIN1):c.700C>T (p.Arg234Cys),BIN1,"R234C, R203C, R207C, R179C","Myopathy, centronuclear, 2","Likely pathogenic(Last reviewed: Jan 8, 2019)","criteria provided, single submitter",VCV000617681,2,127821221,2,127063645,617681,609084,rs777176261,NC_000002.12:127063644:G:A,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
788,NM_001001344.3(ATP2B3):c.197C>T (p.Ser66Leu),ATP2B3,S66L,Fetal akinesia sequence|Arthrogryposis multipl...,"Likely pathogenic(Last reviewed: Jun 28, 2019)","criteria provided, single submitter",VCV000692299,X,152801902,X,153536444,692299,680137,rs1603040061,NC_000023.11:153536443:C:T,NaN
789,NM_001001344.3(ATP2B3):c.2770A>G (p.Thr924Ala),ATP2B3,T924A,"Spinocerebellar ataxia, X-linked 1","Likely pathogenic(Last reviewed: May 13, 2021)","criteria provided, single submitter",VCV001098287,X,152825331,X,153559873,1098287,1086997,NaN,NC_000023.11:153559872:A:G,NaN
790,NM_001001344.3(ATP2B3):c.3320G>A (p.Gly1107Asp),ATP2B3,G1107D,"not provided|Spinocerebellar ataxia, X-linked 1","Likely pathogenic(Last reviewed: Mar 15, 2017)","criteria provided, single submitter",VCV000039839,X,152830539,X,153565081,39839,48438,rs397514619,NC_000023.11:153565080:G:A,NaN
791,NM_001001344.3(ATP2B3):c.3338C>T (p.Thr1113Met),ATP2B3,T1113M,Inborn genetic diseases,"Likely pathogenic(Last reviewed: Jun 29, 2013)","criteria provided, single submitter",VCV000225046,X,152830557,X,153565099,225046,226988,rs368215361,NC_000023.11:153565098:C:T,NaN
792,NM_001001344.3(ATP2B3):c.3594G>T (p.Lys1198Asn),ATP2B3,K1198N,"Spinocerebellar ataxia, X-linked 1|Oral-pharyn...","Likely pathogenic(Last reviewed: Nov 25, 2019)","criteria provided, single submitter",VCV000242886,X,152845687,X,153580229,242886,244001,rs782596945,NC_000023.11:153580228:G:T,NaN

In [8]:
# Select the Gene(s) and Protein change columns to convert it into an easly understandable dataframe
df2_ms_p = df_ms_p[["Gene(s)", "Protein change"]]
df2_ms_p

    Gene(s)              Protein change
0     EPHB2         G786R, G787R, G728R
1       TNR                D199N, D532N
2       TNR                 A397T, A64T
3    SPTBN1                V258M, V271M
4      BIN1  R234C, R203C, R207C, R179C
..      ...                         ...
788  ATP2B3                        S66L
789  ATP2B3                       T924A
790  ATP2B3                      G1107D
791  ATP2B3                      T1113M
792  ATP2B3                      K1198N

[793 rows x 2 columns]

In [9]:
# Get the 1st Prot change and separate it into 3 new columns
df2_ms_p['Prot change'] = df2_ms_p['Protein change'].str.split(',').str[0]
df2_ms_p = df2_ms_p.drop(['Protein change'], axis=1)
df2_ms_p[['firstcol', 'secondcol', 'thirdcol']] = df2_ms_p['Prot change'].str.extract('([A-Za-z]+)(\d+\.?\d*)([A-Za-z]*)', expand = True)
df2_ms_p

C:\Users\sergi\AppData\Local\Temp/ipykernel_15016/10154780.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_ms_p['Prot change'] = df2_ms_p['Protein change'].str.split(',').str[0]

    Gene(s) Prot change firstcol secondcol thirdcol
0     EPHB2       G786R        G       786        R
1       TNR       D199N        D       199        N
2       TNR       A397T        A       397        T
3    SPTBN1       V258M        V       258        M
4      BIN1       R234C        R       234        C
..      ...         ...      ...       ...      ...
788  ATP2B3        S66L        S        66        L
789  ATP2B3       T924A        T       924        A
790  ATP2B3      G1107D        G      1107        D
791  ATP2B3      T1113M        T      1113        M
792  ATP2B3      K1198N        K      1198        N

[793 rows x 5 columns]

In [10]:
# Add the type of Protein change
df2_ms_p["Molecular Consequence"] = 'Missense'
df2_ms_p

    Gene(s) Prot change firstcol secondcol thirdcol Molecular Consequence
0     EPHB2       G786R        G       786        R              Missense
1       TNR       D199N        D       199        N              Missense
2       TNR       A397T        A       397        T              Missense
3    SPTBN1       V258M        V       258        M              Missense
4      BIN1       R234C        R       234        C              Missense
..      ...         ...      ...       ...      ...                   ...
788  ATP2B3        S66L        S        66        L              Missense
789  ATP2B3       T924A        T       924        A              Missense
790  ATP2B3      G1107D        G      1107        D              Missense
791  ATP2B3      T1113M        T      1113        M              Missense
792  ATP2B3      K1198N        K      1198        N              Missense

[793 rows x 6 columns]

# Nonsense

In [11]:
df_ns_p = open_df('likely_ns.txt')
df_ns_p

,Name,Gene(s),Protein change,Condition(s),Clinical significance (Last reviewed),Review status,Accession,GRCh37Chromosome,GRCh37Location,GRCh38Chromosome,GRCh38Location,VariationID,AlleleID(s),dbSNP ID,Canonical SPDI,Unnamed: 15
0,NM_139343.3(BIN1):c.1723A>T (p.Lys575Ter),BIN1,"K575*, K436*, K367*, K488*, K500*, K532*, K406...","Myopathy, centronuclear, 2","Likely pathogenic(Last reviewed: Jan 8, 2019)","criteria provided, single submitter",VCV000008299,2,127806161,2,127048585,8299,23338,rs121909275,NC_000002.12:127048584:T:A,NaN
1,NM_001040142.2(SCN2A):c.1528C>T (p.Gln510Ter),SCN2A,Q510*,Complex neurodevelopmental disorder,"Likely pathogenic(Last reviewed: Oct 22, 2018)",no assertion criteria provided,VCV000984829,2,166172125,2,165315615,984829,972909,rs1553569659,NC_000002.12:165315614:C:T,NaN
2,NM_001040142.2(SCN2A):c.1676_1679del (p.Ser558...,SCN2A,NaN,not provided,Likely pathogenic,no assertion criteria provided,VCV000191305,2,166179668 - 166179671,2,165323158 - 165323161,191305,189108,rs786205635,NC_000002.12:165323157:CTTACT:CT,NaN
3,NM_001040142.2(SCN2A):c.2217G>A (p.Trp739Ter),SCN2A,W739*,not provided,"Likely pathogenic(Last reviewed: Nov 1, 2019)","criteria provided, single submitter",VCV000872402,2,166187907,2,165331397,872402,859021,rs868074288,NC_000002.12:165331396:G:A,NaN
4,NM_001040142.2(SCN2A):c.2548C>T (p.Arg850Ter),SCN2A,R850*,"Seizures, benign familial infantile, 3|Early i...",Pathogenic/Likely pathogenic(Last reviewed: Ja...,"criteria provided, multiple submitters, no con...",VCV000493288,2,166198965,2,165342455,493288,486251,rs1553578503,NC_000002.12:165342454:C:T,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,NM_001939.3(DRP2):c.973C>T (p.Gln325Ter),DRP2,"Q325*, Q247*",not provided,"Likely pathogenic(Last reviewed: Jan 1, 2018)","criteria provided, single submitter",VCV000547090,X,100497458,X,101242469,547090,537579,rs1556419606,NC_000023.11:101242468:C:T,NaN
101,NM_002578.5(PAK3):c.298C>T (p.Arg100Ter),PAK3,"R100*, R115*, R136*, R121*","not provided|Mental retardation 30, X-linked",Pathogenic/Likely pathogenic(Last reviewed: No...,"criteria provided, multiple submitters, no con...",VCV000438299,X,110390986,X,111147758,438299,431930,rs780775497,NC_000023.11:111147757:C:T,NaN
102,NM_002578.5(PAK3):c.403C>T (p.Gln135Ter),PAK3,"Q135*, Q150*, Q156*, Q171*","Mental retardation 30, X-linked","Likely pathogenic(Last reviewed: Aug 6, 2020)","criteria provided, single submitter",VCV000981057,X,110391091,X,111147863,981057,969136,rs2093969640,NC_000023.11:111147862:C:T,NaN
103,NM_002578.5(PAK3):c.1066G>T (p.Glu356Ter),PAK3,"E356*, E371*, E377*, E392*","Mental retardation 30, X-linked",Likely pathogenic,"criteria provided, single submitter",VCV001172599,X,110437602,X,111194374,1172599,1161857,NaN,NC_000023.11:111194373:G:T,NaN
104,NM_001448.3(GPC4):c.1183C>T (p.Gln395Ter),GPC4,Q395*,not provided,"Likely pathogenic(Last reviewed: Sep 1, 2021)","criteria provided, single submitter",VCV001299207,X,132438862,X,133304834,1299207,1289068,NaN,NC_000023.11:133304833:G:A,NaN

In [12]:
# Select the Gene(s) and Protein change columns to convert it into an easly understandable dataframe
df2_ns_p = df_ns_p[["Gene(s)", "Protein change"]]
df2_ns_p

    Gene(s)                                     Protein change
0      BIN1  K575*, K436*, K367*, K488*, K500*, K532*, K406...
1     SCN2A                                              Q510*
2     SCN2A                                                NaN
3     SCN2A                                              W739*
4     SCN2A                                              R850*
..      ...                                                ...
100    DRP2                                       Q325*, Q247*
101    PAK3                         R100*, R115*, R136*, R121*
102    PAK3                         Q135*, Q150*, Q156*, Q171*
103    PAK3                         E356*, E371*, E377*, E392*
104    GPC4                                              Q395*

[105 rows x 2 columns]

In [13]:
# Get the 1st Prot change and separate it into 3 new columns
df2_ns_p['Prot change'] = df2_ns_p['Protein change'].str.split(',').str[0]
df2_ns_p = df2_ns_p.drop(['Protein change'], axis=1)
df2_ns_p[['firstcol', 'secondcol', 'thirdcol']] = df2_ns_p['Prot change'].str.extract('([A-Za-z]+)(\d+\.?\d*)([A-Za-z]*)', expand = True)
df2_ns_p

C:\Users\sergi\AppData\Local\Temp/ipykernel_15016/3778762521.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_ns_p['Prot change'] = df2_ns_p['Protein change'].str.split(',').str[0]

    Gene(s) Prot change firstcol secondcol thirdcol
0      BIN1       K575*        K       575
1     SCN2A       Q510*        Q       510
2     SCN2A         NaN      NaN       NaN      NaN
3     SCN2A       W739*        W       739
4     SCN2A       R850*        R       850
..      ...         ...      ...       ...      ...
100    DRP2       Q325*        Q       325
101    PAK3       R100*        R       100
102    PAK3       Q135*        Q       135
103    PAK3       E356*        E       356
104    GPC4       Q395*        Q       395

[105 rows x 5 columns]

In [14]:
# Fill everything with NA's to then replace them into ns which means nonsense
df2_ns_p = df2_ns_p.replace('', np.nan)
df2_ns_p['thirdcol'].fillna('ns', inplace=True)
df2_ns_p

    Gene(s) Prot change firstcol secondcol thirdcol
0      BIN1       K575*        K       575       ns
1     SCN2A       Q510*        Q       510       ns
2     SCN2A         NaN      NaN       NaN       ns
3     SCN2A       W739*        W       739       ns
4     SCN2A       R850*        R       850       ns
..      ...         ...      ...       ...      ...
100    DRP2       Q325*        Q       325       ns
101    PAK3       R100*        R       100       ns
102    PAK3       Q135*        Q       135       ns
103    PAK3       E356*        E       356       ns
104    GPC4       Q395*        Q       395       ns

[105 rows x 5 columns]

In [15]:
# Add the type of Protein change
df2_ns_p["Molecular Consequence"] = 'Nonsense'
df2_ns_p

    Gene(s) Prot change firstcol secondcol thirdcol Molecular Consequence
0      BIN1       K575*        K       575       ns              Nonsense
1     SCN2A       Q510*        Q       510       ns              Nonsense
2     SCN2A         NaN      NaN       NaN       ns              Nonsense
3     SCN2A       W739*        W       739       ns              Nonsense
4     SCN2A       R850*        R       850       ns              Nonsense
..      ...         ...      ...       ...      ...                   ...
100    DRP2       Q325*        Q       325       ns              Nonsense
101    PAK3       R100*        R       100       ns              Nonsense
102    PAK3       Q135*        Q       135       ns              Nonsense
103    PAK3       E356*        E       356       ns              Nonsense
104    GPC4       Q395*        Q       395       ns              Nonsense

[105 rows x 6 columns]

# Splicesites

In [16]:
df_ss_p = open_df('likely_ss.txt')
df_ss_p

,Name,Gene(s),Protein change,Condition(s),Clinical significance (Last reviewed),Review status,Accession,GRCh37Chromosome,GRCh37Location,GRCh38Chromosome,GRCh38Location,VariationID,AlleleID(s),dbSNP ID,Canonical SPDI,Unnamed: 15
0,NM_001330311.2(DVL1):c.1715-1G>A,DVL1,NaN,"Robinow syndrome, autosomal dominant 2","Likely pathogenic(Last reviewed: Oct 22, 2019)",no assertion criteria provided,VCV000981468,1,1271896,1,1336516,981468,969551,NaN,NC_000001.11:1336515:C:T,NaN
1,NM_139343.3(BIN1):c.1132-2A>G,BIN1,NaN,"Myopathy, centronuclear, 2","Likely pathogenic(Last reviewed: Jun 12, 2018)","criteria provided, single submitter",VCV000566386,2,127811590,2,127054014,566386,557545,rs1295546366,NC_000002.12:127054013:T:C,NaN
2,NM_139343.3(BIN1):c.1002+2T>C,BIN1,NaN,"Myopathy, centronuclear, 2|not provided","Likely pathogenic(Last reviewed: Jun 20, 2016)","criteria provided, single submitter",VCV000432181,2,127816585,2,127059009,432181,425396,rs1553458019,NC_000002.12:127059008:A:G,NaN
3,NM_001040142.2(SCN2A):c.971-1G>A,SCN2A,NaN,Early infantile epileptic encephalopathy 11,"Likely pathogenic(Last reviewed: Oct 2, 2021)","criteria provided, single submitter",VCV001320083,2,166168534,2,165312024,1320083,1310328,NaN,NC_000002.12:165312023:G:A,NaN
4,NM_001040142.2(SCN2A):c.1384-2A>G,SCN2A,NaN,"Seizures, benign familial infantile, 3","Likely pathogenic(Last reviewed: May 28, 2019)","criteria provided, single submitter",VCV000801777,2,166171979,2,165315469,801777,790074,rs1574571769,NC_000002.12:165315468:A:G,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,NM_002547.3(OPHN1):c.1105-13_1109del,OPHN1,NaN,Mental retardation X-linked with cerebellar hy...,"Likely pathogenic(Last reviewed: Sep 10, 2020)",no assertion criteria provided,VCV000992999,X,67414336 - 67414353,X,68194494 - 68194511,992999,980975,rs2077502210,NC_000023.11:68194493:TAGATCTACAAAAGAAGATA:TA,NaN
140,NM_002547.3(OPHN1):c.1105-1G>T,OPHN1,NaN,not provided,"Likely pathogenic(Last reviewed: Mar 1, 2017)","criteria provided, single submitter",VCV000444808,X,67414341,X,68194499,444808,438448,rs1555951715,NC_000023.11:68194498:C:A,NaN
141,NM_002547.3(OPHN1):c.1025+2T>C,OPHN1,NaN,not provided,"Likely pathogenic(Last reviewed: Feb 1, 2019)","criteria provided, single submitter",VCV000807740,X,67421459,X,68201617,807740,798373,rs1602231145,NC_000023.11:68201616:A:G,NaN
142,NM_021120.4(DLG3):c.840+1G>A,DLG3,NaN,not provided,"Likely pathogenic(Last reviewed: Oct 23, 2020)","criteria provided, single submitter",VCV000987128,X,69670156,X,70450306,987128,975644,rs1212006965,NC_000023.11:70450305:G:A,NaN
143,NM_021120.4(DLG3):c.1520+1G>T,DLG3,NaN,See cases,"Likely pathogenic(Last reviewed: Apr 26, 2021)","criteria provided, single submitter",VCV001098381,X,69699115,X,70479265,1098381,1087116,NaN,NC_000023.11:70479264:G:T,NaN

In [17]:
# Select the Gene(s) and Protein change columns to convert it into an easly understandable dataframe
df2_ss_p = df_ss_p[["Gene(s)", "Protein change"]]
df2_ss_p

    Gene(s) Protein change
0      DVL1            NaN
1      BIN1            NaN
2      BIN1            NaN
3     SCN2A            NaN
4     SCN2A            NaN
..      ...            ...
139   OPHN1            NaN
140   OPHN1            NaN
141   OPHN1            NaN
142    DLG3            NaN
143    DLG3            NaN

[144 rows x 2 columns]

In [18]:
# Get the 1st Prot change and separate it into 3 new columns
df2_ss_p['Prot change'] = df2_ss_p['Protein change'].str.split(',').str[0]
df2_ss_p = df2_ss_p.drop(['Protein change'], axis=1)
df2_ss_p[['firstcol', 'secondcol', 'thirdcol']] = df2_ss_p['Prot change'].str.extract('([A-Za-z]+)(\d+\.?\d*)([A-Za-z]*)', expand = True)
df2_ss_p

C:\Users\sergi\AppData\Local\Temp/ipykernel_15016/2730484892.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_ss_p['Prot change'] = df2_ss_p['Protein change'].str.split(',').str[0]

    Gene(s) Prot change firstcol secondcol thirdcol
0      DVL1         NaN      NaN       NaN      NaN
1      BIN1         NaN      NaN       NaN      NaN
2      BIN1         NaN      NaN       NaN      NaN
3     SCN2A         NaN      NaN       NaN      NaN
4     SCN2A         NaN      NaN       NaN      NaN
..      ...         ...      ...       ...      ...
139   OPHN1         NaN      NaN       NaN      NaN
140   OPHN1         NaN      NaN       NaN      NaN
141   OPHN1         NaN      NaN       NaN      NaN
142    DLG3         NaN      NaN       NaN      NaN
143    DLG3         NaN      NaN       NaN      NaN

[144 rows x 5 columns]

In [19]:
# Add the type of Protein change
df2_ss_p["Molecular Consequence"] = 'Splicesites'
df2_ss_p

    Gene(s) Prot change firstcol secondcol thirdcol Molecular Consequence
0      DVL1         NaN      NaN       NaN      NaN           Splicesites
1      BIN1         NaN      NaN       NaN      NaN           Splicesites
2      BIN1         NaN      NaN       NaN      NaN           Splicesites
3     SCN2A         NaN      NaN       NaN      NaN           Splicesites
4     SCN2A         NaN      NaN       NaN      NaN           Splicesites
..      ...         ...      ...       ...      ...                   ...
139   OPHN1         NaN      NaN       NaN      NaN           Splicesites
140   OPHN1         NaN      NaN       NaN      NaN           Splicesites
141   OPHN1         NaN      NaN       NaN      NaN           Splicesites
142    DLG3         NaN      NaN       NaN      NaN           Splicesites
143    DLG3         NaN      NaN       NaN      NaN           Splicesites

[144 rows x 6 columns]

# Last touches Pathogenic

In [20]:
# Join all 4 dataframes and rename index to have correct numbers
df_final_p = pd.concat([df2_fs_p, df2_ms_p, df2_ns_p, df2_ss_p])
df_final_p.index = range(len(df_final_p))
df_final_p

     Gene(s) Prot change firstcol secondcol thirdcol Molecular Consequence
0       DVL1      S578fs        S       578       fs            Frameshift
1       DVL1      T565fs        T       565       fs            Frameshift
2       DVL1      S562fs        S       562       fs            Frameshift
3       DVL1      S542fs        S       542       fs            Frameshift
4       DVL1      S564fs        S       564       fs            Frameshift
...      ...         ...      ...       ...      ...                   ...
1916   OPHN1         NaN      NaN       NaN      NaN           Splicesites
1917   OPHN1         NaN      NaN       NaN      NaN           Splicesites
1918   OPHN1         NaN      NaN       NaN      NaN           Splicesites
1919    DLG3         NaN      NaN       NaN      NaN           Splicesites
1920    DLG3         NaN      NaN       NaN      NaN           Splicesites

[1921 rows x 6 columns]

In [21]:
# Add The Clinical Significance
df_final_p["Clinical Significance"] = 'Pathogenic'
df_final_p

,Gene(s),Prot change,firstcol,secondcol,thirdcol,Molecular Consequence,Clinical Significance
0,DVL1,S578fs,S,578,fs,Frameshift,Pathogenic
1,DVL1,T565fs,T,565,fs,Frameshift,Pathogenic
2,DVL1,S562fs,S,562,fs,Frameshift,Pathogenic
3,DVL1,S542fs,S,542,fs,Frameshift,Pathogenic
4,DVL1,S564fs,S,564,fs,Frameshift,Pathogenic
...,...,...,...,...,...,...,...
1916,OPHN1,NaN,NaN,NaN,NaN,Splicesites,Pathogenic
1917,OPHN1,NaN,NaN,NaN,NaN,Splicesites,Pathogenic
1918,OPHN1,NaN,NaN,NaN,NaN,Splicesites,Pathogenic
1919,DLG3,NaN,NaN,NaN,NaN,Splicesites,Pathogenic
1920,DLG3,NaN,NaN,NaN,NaN,Splicesites,Pathogenic

# Likely Pathogenic

# Frameshift

In [22]:
df_fs_lp = open_df('path_fs.txt')
df_fs_p

,Name,Gene(s),Protein change,Condition(s),Clinical significance (Last reviewed),Review status,Accession,GRCh37Chromosome,GRCh37Location,GRCh38Chromosome,GRCh38Location,VariationID,AlleleID(s),dbSNP ID,Canonical SPDI,Unnamed: 15
0,NM_001330311.2(DVL1):c.1731del (p.Ser578fs),DVL1,"S578fs, S553fs","Robinow syndrome, autosomal dominant 2|not pro...","Likely pathogenic(Last reviewed: Jul 29, 2020)","criteria provided, single submitter",VCV000504195,1,1271879,1,1336499,504195,495052,rs1553172962,NC_000001.11:1336498:CCC:CC,NaN
1,NM_001330311.2(DVL1):c.1694_1706del (p.Thr565fs),DVL1,"T565fs, T540fs",not provided,"Likely pathogenic(Last reviewed: Mar 23, 2018)","criteria provided, single submitter",VCV000524041,1,1273365 - 1273377,1,1337985 - 1337997,524041,514413,rs1553173356,NC_000001.11:1337984:TGCTGACTCCCGGTGCTG:TGCTG,NaN
2,NM_001330311.2(DVL1):c.1683_1698del (p.Ser562fs),DVL1,"S562fs, S537fs","Robinow syndrome, autosomal dominant 2","Likely pathogenic(Last reviewed: Jun 1, 2017)","criteria provided, single submitter",VCV000488048,1,1273373 - 1273388,1,1337993 - 1338008,488048,481060,rs1553173368,NC_000001.11:1337992:CCCGGTGCTGCCGCTGCC:CC,NaN
3,NM_001330311.2(DVL1):c.1698del (p.Ser567fs),DVL1,"S542fs, S567fs","Robinow syndrome, autosomal dominant 2","Likely pathogenic(Last reviewed: Jun 1, 2017)","criteria provided, single submitter",VCV000488046,1,1273373,1,1337993,488046,481061,rs1553173367,NC_000001.11:1337992:CCC:CC,NaN
4,NM_001330311.2(DVL1):c.1687_1691dup (p.Ser564fs),DVL1,"S564fs, S539fs","Robinow syndrome, autosomal dominant 2","Likely pathogenic(Last reviewed: Jun 1, 2017)","criteria provided, single submitter",VCV000488045,1,1273379 - 1273380,1,1337999 - 1338000,488045,481062,rs1553173372,NC_000001.11:1337999:CTGCC:CTGCCCTGCC,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
874,NM_002578.5(PAK3):c.490_491insGGAG (p.Pro164fs),PAK3,"P164fs, P185fs, P179fs, P200fs",not provided,"Pathogenic(Last reviewed: Feb 1, 2019)","criteria provided, single submitter",VCV000870778,X,110406164 - 110406165,X,111162936 - 111162937,870778,860768,rs2094208830,NC_000023.11:111162936::GGAG,NaN
875,NM_001448.3(GPC4):c.1518_1521dup (p.Pro508fs),GPC4,P508fs,Keipert syndrome,"Pathogenic(Last reviewed: Feb 1, 2019)",no assertion criteria provided,VCV000626360,X,132437044 - 132437045,X,133303016 - 133303017,626360,614692,rs1569339879,NC_000023.11:133303016:GCAC:GCACGCAC,NaN
876,NM_001448.3(GPC4):c.742del (p.Leu248fs),GPC4,L248fs,Keipert syndrome,"Pathogenic(Last reviewed: Feb 1, 2019)",no assertion criteria provided,VCV000626361,X,132445421,X,133311393,626361,614693,rs1569341521,NC_000023.11:133311392:GGG:GG,NaN
877,NM_001448.3(GPC4):c.701dup (p.Val235fs),GPC4,V235fs,Keipert syndrome,"Pathogenic(Last reviewed: Jun 14, 2019)",no assertion criteria provided,VCV000547176,X,132458182 - 132458183,X,133324154 - 133324155,547176,537664,rs1556025980,NC_000023.11:133324154:TT:TTT,NaN
878,NM_001448.3(GPC4):c.316del (p.Asp106fs),GPC4,D106fs,Keipert syndrome,"Pathogenic(Last reviewed: Jun 14, 2019)",no assertion criteria provided,VCV000547178,X,132473214,X,133339186,547178,537665,rs1556028269,NC_000023.11:133339185:C:,NaN

In [23]:
# Select the Gene(s) and Protein change columns to convert it into an easly understandable dataframe
df2_fs_lp = df_fs_lp[["Gene(s)", "Protein change"]]
df2_fs_lp

    Gene(s)                  Protein change
0      DVL1                  S539fs, S564fs
1      DVL1                  P531fs, P556fs
2      DVL1                  P551fs, P526fs
3      DVL1                  F524fs, F549fs
4      DVL1                  P521fs, P546fs
..      ...                             ...
739    PAK3  P164fs, P185fs, P179fs, P200fs
740    GPC4                          P508fs
741    GPC4                          L248fs
742    GPC4                          V235fs
743    GPC4                          D106fs

[744 rows x 2 columns]

In [24]:
# Get the 1st Prot change and separate it into 3 new columns
df2_fs_lp['Prot change'] = df2_fs_lp['Protein change'].str.split(',').str[0]
df2_fs_lp = df2_fs_lp.drop(['Protein change'], axis=1)
df2_fs_lp[['firstcol', 'secondcol', 'thirdcol']] = df2_fs_lp['Prot change'].str.extract('([A-Za-z]+)(\d+\.?\d*)([A-Za-z]*)', expand = True)
df2_fs_lp

C:\Users\sergi\AppData\Local\Temp/ipykernel_15016/1103195182.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_fs_lp['Prot change'] = df2_fs_lp['Protein change'].str.split(',').str[0]

    Gene(s) Prot change firstcol secondcol thirdcol
0      DVL1      S539fs        S       539       fs
1      DVL1      P531fs        P       531       fs
2      DVL1      P551fs        P       551       fs
3      DVL1      F524fs        F       524       fs
4      DVL1      P521fs        P       521       fs
..      ...         ...      ...       ...      ...
739    PAK3      P164fs        P       164       fs
740    GPC4      P508fs        P       508       fs
741    GPC4      L248fs        L       248       fs
742    GPC4      V235fs        V       235       fs
743    GPC4      D106fs        D       106       fs

[744 rows x 5 columns]

In [25]:
# Add the type of Protein change
df2_fs_lp["Molecular Consequence"] = 'Frameshift'
df2_fs_lp

    Gene(s) Prot change firstcol secondcol thirdcol Molecular Consequence
0      DVL1      S539fs        S       539       fs            Frameshift
1      DVL1      P531fs        P       531       fs            Frameshift
2      DVL1      P551fs        P       551       fs            Frameshift
3      DVL1      F524fs        F       524       fs            Frameshift
4      DVL1      P521fs        P       521       fs            Frameshift
..      ...         ...      ...       ...      ...                   ...
739    PAK3      P164fs        P       164       fs            Frameshift
740    GPC4      P508fs        P       508       fs            Frameshift
741    GPC4      L248fs        L       248       fs            Frameshift
742    GPC4      V235fs        V       235       fs            Frameshift
743    GPC4      D106fs        D       106       fs            Frameshift

[744 rows x 6 columns]

# Missense

In [26]:
df_ms_lp = open_df('path_ms.txt')
df_ms_lp

,Name,Gene(s),Protein change,Condition(s),Clinical significance (Last reviewed),Review status,Accession,GRCh37Chromosome,GRCh37Location,GRCh38Chromosome,GRCh38Location,VariationID,AlleleID(s),dbSNP ID,Canonical SPDI,Unnamed: 15
0,NM_017449.5(EPHB2):c.2233C>T (p.Arg745Cys),EPHB2,"R745C, R746C, R687C","Bleeding disorder, platelet-type, 22","Pathogenic(Last reviewed: Jun 11, 2019)",no assertion criteria provided,VCV000633783,1,23234542,1,22908049,633783,622215,rs761749948,NC_000001.11:22908048:C:T,NaN
1,NM_002143.3(HPCA):c.212C>A (p.Thr71Asn),HPCA,T71N,Torsion dystonia 2,"Pathogenic(Last reviewed: Apr 2, 2015)",no assertion criteria provided,VCV000190119,1,33354711,1,32889110,190119,187951,rs775863165,NC_000001.11:32889109:C:A,NaN
2,NM_002143.3(HPCA):c.225C>A (p.Asn75Lys),HPCA,N75K,Torsion dystonia 2,"Pathogenic(Last reviewed: Apr 2, 2015)",no assertion criteria provided,VCV000190118,1,33354724,1,32889123,190118,187950,rs786205675,NC_000001.11:32889122:C:A,NaN
3,NM_002143.3(HPCA):c.568G>A (p.Ala190Thr),HPCA,A190T,Torsion dystonia 2,"Pathogenic(Last reviewed: Apr 2, 2015)",no assertion criteria provided,VCV000190120,1,33359449,1,32893848,190120,187952,rs550921485,NC_000001.11:32893847:G:A,NaN
4,NM_001010898.4(SLC6A17):c.484G>A (p.Gly162Arg),SLC6A17,G162R,"Mental retardation, autosomal recessive 48","Pathogenic(Last reviewed: Mar 5, 2015)",no assertion criteria provided,VCV000187769,1,110716634,1,110174012,187769,185667,rs775085213,NC_000001.11:110174011:G:A,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586,NM_181303.2(NLGN3):c.1600C>T (p.Pro534Ser),NLGN3,"P514S, P397S, P494S, P534S",Autistic behavior|Intellectual disability,"Pathogenic(Last reviewed: May 7, 2019)","criteria provided, single submitter",VCV000631481,X,70387547,X,71167697,631481,619844,rs1569485503,NC_000023.11:71167696:C:T,NaN
587,NM_002578.5(PAK3):c.199C>T (p.Arg67Cys),PAK3,R67C,"Mental retardation 30, X-linked","Pathogenic(Last reviewed: Aug 14, 2000)",no assertion criteria provided,VCV000011569,X,110385347,X,111142119,11569,26608,rs121434612,NC_000023.11:111142118:C:T,NaN
588,NM_002578.5(PAK3):c.976G>C (p.Val326Leu),PAK3,"V341L, V362L, V326L, V347L",Microcephaly|Intellectual disability,"Pathogenic(Last reviewed: Mar 24, 2019)","criteria provided, single submitter",VCV000684413,X,110435830,X,111192602,684413,672009,rs1603373827,NC_000023.11:111192601:G:C,NaN
589,NM_002578.5(PAK3):c.1094C>A (p.Ala365Glu),PAK3,"A365E, A386E, A401E, A380E","Mental retardation 30, X-linked","Pathogenic(Last reviewed: Aug 1, 2003)",no assertion criteria provided,VCV000011570,X,110437630,X,111194402,11570,26609,rs121434613,NC_000023.11:111194401:C:A,NaN
590,NM_002578.5(PAK3):c.1337G>C (p.Trp446Ser),PAK3,"W446S, W467S, W461S, W482S","Mental retardation 30, X-linked","Pathogenic(Last reviewed: Oct 15, 2007)",no assertion criteria provided,VCV000011571,X,110439798,X,111196570,11571,26610,rs121434614,NC_000023.11:111196569:G:C,NaN

In [27]:
# Select the Gene(s) and Protein change columns to convert it into an easly understandable dataframe
df2_ms_lp = df_ms_lp[["Gene(s)", "Protein change"]]
df2_ms_lp

     Gene(s)              Protein change
0      EPHB2         R745C, R746C, R687C
1       HPCA                        T71N
2       HPCA                        N75K
3       HPCA                       A190T
4    SLC6A17                       G162R
..       ...                         ...
586    NLGN3  P514S, P397S, P494S, P534S
587     PAK3                        R67C
588     PAK3  V341L, V362L, V326L, V347L
589     PAK3  A365E, A386E, A401E, A380E
590     PAK3  W446S, W467S, W461S, W482S

[591 rows x 2 columns]

In [28]:
# Get the 1st Prot change and separate it into 3 new columns
df2_ms_lp['Prot change'] = df2_ms_lp['Protein change'].str.split(',').str[0]
df2_ms_lp = df2_ms_lp.drop(['Protein change'], axis=1)
df2_ms_lp[['firstcol', 'secondcol', 'thirdcol']] = df2_ms_lp['Prot change'].str.extract('([A-Za-z]+)(\d+\.?\d*)([A-Za-z]*)', expand = True)
df2_ms_lp

C:\Users\sergi\AppData\Local\Temp/ipykernel_15016/4221618704.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_ms_lp['Prot change'] = df2_ms_lp['Protein change'].str.split(',').str[0]

     Gene(s) Prot change firstcol secondcol thirdcol
0      EPHB2       R745C        R       745        C
1       HPCA        T71N        T        71        N
2       HPCA        N75K        N        75        K
3       HPCA       A190T        A       190        T
4    SLC6A17       G162R        G       162        R
..       ...         ...      ...       ...      ...
586    NLGN3       P514S        P       514        S
587     PAK3        R67C        R        67        C
588     PAK3       V341L        V       341        L
589     PAK3       A365E        A       365        E
590     PAK3       W446S        W       446        S

[591 rows x 5 columns]

In [29]:
# Add the type of Protein change
df2_ms_lp["Molecular Consequence"] = 'Missense'
df2_ms_lp

     Gene(s) Prot change firstcol secondcol thirdcol Molecular Consequence
0      EPHB2       R745C        R       745        C              Missense
1       HPCA        T71N        T        71        N              Missense
2       HPCA        N75K        N        75        K              Missense
3       HPCA       A190T        A       190        T              Missense
4    SLC6A17       G162R        G       162        R              Missense
..       ...         ...      ...       ...      ...                   ...
586    NLGN3       P514S        P       514        S              Missense
587     PAK3        R67C        R        67        C              Missense
588     PAK3       V341L        V       341        L              Missense
589     PAK3       A365E        A       365        E              Missense
590     PAK3       W446S        W       446        S              Missense

[591 rows x 6 columns]

# Nonsense

In [30]:
df_ns_lp = open_df('path_ns.txt')
df_ns_lp

,Name,Gene(s),Protein change,Condition(s),Clinical significance (Last reviewed),Review status,Accession,GRCh37Chromosome,GRCh37Location,GRCh38Chromosome,GRCh38Location,VariationID,AlleleID(s),dbSNP ID,Canonical SPDI,Unnamed: 15
0,NM_017449.5(EPHB2):c.2164C>T (p.Gln722Ter),EPHB2,"Q723*, Q722*, Q664*",Prostate cancer/brain cancer susceptibility,"Pathogenic(Last reviewed: Sep 1, 2004)",no assertion criteria provided,VCV000008532,1,23234473,1,22907980,8532,23571,rs121912582,NC_000001.11:22907979:C:T,NaN
1,NM_003285.3(TNR):c.2713C>T (p.Arg905Ter),TNR,"R572*, R905*","NEURODEVELOPMENTAL DISORDER, NONPROGRESSIVE, W...","Pathogenic(Last reviewed: Jul 25, 2019)","criteria provided, single submitter",VCV000691951,1,175331940,1,175362804,691951,679701,rs1287757170,NC_000001.11:175362803:G:A,NaN
2,NM_003285.3(TNR):c.207C>G (p.Tyr69Ter),TNR,Y69*,Non-progressive neurodevelopmental disorder wi...,"Pathogenic(Last reviewed: Jul 25, 2019)","criteria provided, single submitter",VCV000691955,1,175375644,1,175406508,691955,679705,rs1389178206,NC_000001.11:175406507:G:C,NaN
3,NM_003128.3(SPTBN1):c.549C>A (p.Cys183Ter),SPTBN1,"C183*, C170*","DEVELOPMENTAL DELAY, IMPAIRED SPEECH, AND BEHA...","Pathogenic(Last reviewed: Aug 11, 2021)",no assertion criteria provided,VCV001195995,2,54843418,2,54616281,1195995,1186000,NaN,NC_000002.12:54616280:C:A,NaN
4,NM_003128.3(SPTBN1):c.2674G>T (p.Glu892Ter),SPTBN1,"E892*, E879*","DEVELOPMENTAL DELAY, IMPAIRED SPEECH, AND BEHA...","Pathogenic(Last reviewed: Aug 11, 2021)",no assertion criteria provided,VCV001195998,2,54857033,2,54629896,1195998,1186003,NaN,NC_000002.12:54629895:G:T,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487,NM_021120.4(DLG3):c.2280T>G (p.Tyr760Ter),DLG3,"Y760*, Y309*, Y455*",not provided,"Pathogenic(Last reviewed: Feb 7, 2014)","criteria provided, single submitter",VCV000166996,X,69720772,X,70500922,166996,177675,rs727503900,NC_000023.11:70500921:T:G,NaN
488,NM_002578.5(PAK3):c.298C>T (p.Arg100Ter),PAK3,"R100*, R115*, R136*, R121*","not provided|Mental retardation 30, X-linked",Pathogenic/Likely pathogenic(Last reviewed: No...,"criteria provided, multiple submitters, no con...",VCV000438299,X,110390986,X,111147758,438299,431930,rs780775497,NC_000023.11:111147757:C:T,NaN
489,NM_002578.5(PAK3):c.1255C>T (p.Arg419Ter),PAK3,"R419*, R455*, R440*, R434*","Mental retardation 30, X-linked|not provided","Pathogenic(Last reviewed: Jan 3, 2018)",no assertion criteria provided,VCV000011568,X,110439716,X,111196488,11568,26607,rs121434611,NC_000023.11:111196487:C:T,NaN
490,NM_001448.3(GPC4):c.1516C>T (p.Gln506Ter),GPC4,Q506*,Keipert syndrome,"Pathogenic(Last reviewed: Oct 2, 2019)","criteria provided, single submitter",VCV000547175,X,132437050,X,133303022,547175,537662,rs1556022641,NC_000023.11:133303021:G:A,NaN
491,NM_001448.3(GPC4):c.1486G>T (p.Glu496Ter),GPC4,E496*,Keipert syndrome,"Pathogenic(Last reviewed: Oct 2, 2019)","criteria provided, single submitter",VCV000547177,X,132437080,X,133303052,547177,537663,rs1556022644,NC_000023.11:133303051:C:A,NaN

In [31]:
# Select the Gene(s) and Protein change columns to convert it into an easly understandable dataframe
df2_ns_lp = df_ns_lp[["Gene(s)", "Protein change"]]
df2_ns_lp

    Gene(s)              Protein change
0     EPHB2         Q723*, Q722*, Q664*
1       TNR                R572*, R905*
2       TNR                        Y69*
3    SPTBN1                C183*, C170*
4    SPTBN1                E892*, E879*
..      ...                         ...
487    DLG3         Y760*, Y309*, Y455*
488    PAK3  R100*, R115*, R136*, R121*
489    PAK3  R419*, R455*, R440*, R434*
490    GPC4                       Q506*
491    GPC4                       E496*

[492 rows x 2 columns]

In [32]:
# Get the 1st Prot change and separate it into 3 new columns
df2_ns_lp['Prot change'] = df2_ns_lp['Protein change'].str.split(',').str[0]
df2_ns_lp = df2_ns_lp.drop(['Protein change'], axis=1)
df2_ns_lp[['firstcol', 'secondcol', 'thirdcol']] = df2_ns_lp['Prot change'].str.extract('([A-Za-z]+)(\d+\.?\d*)([A-Za-z]*)', expand = True)
df2_ns_lp

C:\Users\sergi\AppData\Local\Temp/ipykernel_15016/465718903.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_ns_lp['Prot change'] = df2_ns_lp['Protein change'].str.split(',').str[0]

    Gene(s) Prot change firstcol secondcol thirdcol
0     EPHB2       Q723*        Q       723
1       TNR       R572*        R       572
2       TNR        Y69*        Y        69
3    SPTBN1       C183*        C       183
4    SPTBN1       E892*        E       892
..      ...         ...      ...       ...      ...
487    DLG3       Y760*        Y       760
488    PAK3       R100*        R       100
489    PAK3       R419*        R       419
490    GPC4       Q506*        Q       506
491    GPC4       E496*        E       496

[492 rows x 5 columns]

In [33]:
# Fill everything with NA's to then replace them into ns which means nonsense
df2_ns_lp = df2_ns_lp.replace('', np.nan)
df2_ns_lp['thirdcol'].fillna('ns', inplace=True)
df2_ns_lp

    Gene(s) Prot change firstcol secondcol thirdcol
0     EPHB2       Q723*        Q       723       ns
1       TNR       R572*        R       572       ns
2       TNR        Y69*        Y        69       ns
3    SPTBN1       C183*        C       183       ns
4    SPTBN1       E892*        E       892       ns
..      ...         ...      ...       ...      ...
487    DLG3       Y760*        Y       760       ns
488    PAK3       R100*        R       100       ns
489    PAK3       R419*        R       419       ns
490    GPC4       Q506*        Q       506       ns
491    GPC4       E496*        E       496       ns

[492 rows x 5 columns]

In [34]:
# Add the type of Protein change
df2_ns_lp["Molecular Consequence"] = 'Nonsense'
df2_ns_lp

    Gene(s) Prot change firstcol secondcol thirdcol Molecular Consequence
0     EPHB2       Q723*        Q       723       ns              Nonsense
1       TNR       R572*        R       572       ns              Nonsense
2       TNR        Y69*        Y        69       ns              Nonsense
3    SPTBN1       C183*        C       183       ns              Nonsense
4    SPTBN1       E892*        E       892       ns              Nonsense
..      ...         ...      ...       ...      ...                   ...
487    DLG3       Y760*        Y       760       ns              Nonsense
488    PAK3       R100*        R       100       ns              Nonsense
489    PAK3       R419*        R       419       ns              Nonsense
490    GPC4       Q506*        Q       506       ns              Nonsense
491    GPC4       E496*        E       496       ns              Nonsense

[492 rows x 6 columns]

# Splicesites

In [35]:
df_ss_lp = open_df('path_ss.txt')
df_ss_lp

,Name,Gene(s),Protein change,Condition(s),Clinical significance (Last reviewed),Review status,Accession,GRCh37Chromosome,GRCh37Location,GRCh38Chromosome,GRCh38Location,VariationID,AlleleID(s),dbSNP ID,Canonical SPDI,Unnamed: 15
0,NM_001040142.2(SCN2A):c.386+2T>C,SCN2A,NaN,Complex neurodevelopmental disorder|Inborn gen...,"Pathogenic(Last reviewed: Mar 20, 2018)","criteria provided, multiple submitters, no con...",VCV000449290,2,166153647,2,165297137,449290,442981,rs1553564400,NC_000002.12:165297136:T:C,NaN
1,NM_001040142.2(SCN2A):c.387-2A>G,SCN2A,NaN,not provided,"Pathogenic(Last reviewed: Mar 24, 2017)","criteria provided, single submitter",VCV000207037,2,166164356,2,165307846,207037,201279,rs796053169,NC_000002.12:165307845:A:G,NaN
2,NM_001040142.2(SCN2A):c.476+1G>A,SCN2A,NaN,not provided,"Pathogenic(Last reviewed: May 27, 2021)","criteria provided, single submitter",VCV001206719,2,166164448,2,165307938,1206719,1196712,NaN,NC_000002.12:165307937:G:A,NaN
3,NM_001040142.2(SCN2A):c.605+1G>A,SCN2A,NaN,"Seizures, benign familial infantile, 3|Early i...","Pathogenic(Last reviewed: Feb 14, 2020)","criteria provided, multiple submitters, no con...",VCV000619986,2,166165305,2,165308795,619986,611460,NaN,NC_000002.12:165308794:G:A,NaN
4,NM_001040142.2(SCN2A):c.605+1G>T,SCN2A,NaN,Complex neurodevelopmental disorder|not provided,"Pathogenic(Last reviewed: Jan 25, 2017)","criteria provided, single submitter",VCV000207039,2,166165305,2,165308795,207039,201282,rs796053171,NC_000002.12:165308794:G:T,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,NM_002547.3(OPHN1):c.1138+1G>A,OPHN1,NaN,Mental retardation X-linked with cerebellar hy...,"Pathogenic(Last reviewed: May 28, 2019)","criteria provided, single submitter",VCV000804020,X,67414306,X,68194464,804020,792490,rs1602226670,NC_000023.11:68194463:C:T,NaN
192,NM_002547.3(OPHN1):c.155-2A>C,OPHN1,NaN,not provided,"Pathogenic(Last reviewed: Jun 18, 2015)","criteria provided, single submitter",VCV000419263,X,67518940,X,68299098,419263,411446,rs1064793755,NC_000023.11:68299097:T:G,NaN
193,NM_021120.4(DLG3):c.357+1G>C,DLG3,NaN,X-Linked mental retardation 90,"Pathogenic(Last reviewed: Apr 11, 2014)",no assertion criteria provided,VCV000127193,X,69665409,X,70445559,127193,132677,rs587777359,NC_000023.11:70445558:G:C,NaN
194,NM_021120.4(DLG3):c.985+1G>C,DLG3,NaN,X-Linked mental retardation 90,"Pathogenic(Last reviewed: Apr 11, 2014)",no assertion criteria provided,VCV000127194,X,69670634,X,70450784,127194,132678,rs587777360,NC_000023.11:70450783:G:C,NaN
195,NM_181303.2(NLGN3):c.913+1G>A,NLGN3,NaN,"Autism, susceptibility to, X-linked 1","Pathogenic(Last reviewed: Aug 6, 2021)",no assertion criteria provided,VCV001326919,X,70384179,X,71164329,1326919,1317381,NaN,NC_000023.11:71164328:G:A,NaN

In [36]:
# Select the Gene(s) and Protein change columns to convert it into an easly understandable dataframe
df2_ss_lp = df_ss_lp[["Gene(s)", "Protein change"]]
df2_ss_lp

    Gene(s) Protein change
0     SCN2A            NaN
1     SCN2A            NaN
2     SCN2A            NaN
3     SCN2A            NaN
4     SCN2A            NaN
..      ...            ...
191   OPHN1            NaN
192   OPHN1            NaN
193    DLG3            NaN
194    DLG3            NaN
195   NLGN3            NaN

[196 rows x 2 columns]

In [37]:
# Get the 1st Prot change and separate it into 3 new columns
df2_ss_lp['Prot change'] = df2_ss_lp['Protein change'].str.split(',').str[0]
df2_ss_lp = df2_ss_lp.drop(['Protein change'], axis=1)
df2_ss_lp[['firstcol', 'secondcol', 'thirdcol']] = df2_ss_lp['Prot change'].str.extract('([A-Za-z]+)(\d+\.?\d*)([A-Za-z]*)', expand = True)
df2_ss_lp

C:\Users\sergi\AppData\Local\Temp/ipykernel_15016/109867787.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_ss_lp['Prot change'] = df2_ss_lp['Protein change'].str.split(',').str[0]

    Gene(s) Prot change firstcol secondcol thirdcol
0     SCN2A         NaN      NaN       NaN      NaN
1     SCN2A         NaN      NaN       NaN      NaN
2     SCN2A         NaN      NaN       NaN      NaN
3     SCN2A         NaN      NaN       NaN      NaN
4     SCN2A         NaN      NaN       NaN      NaN
..      ...         ...      ...       ...      ...
191   OPHN1         NaN      NaN       NaN      NaN
192   OPHN1         NaN      NaN       NaN      NaN
193    DLG3         NaN      NaN       NaN      NaN
194    DLG3         NaN      NaN       NaN      NaN
195   NLGN3         NaN      NaN       NaN      NaN

[196 rows x 5 columns]

In [38]:
# Add the type of Protein change
df2_ss_lp["Molecular Consequence"] = 'Splicesites'
df2_ss_lp

    Gene(s) Prot change firstcol secondcol thirdcol Molecular Consequence
0     SCN2A         NaN      NaN       NaN      NaN           Splicesites
1     SCN2A         NaN      NaN       NaN      NaN           Splicesites
2     SCN2A         NaN      NaN       NaN      NaN           Splicesites
3     SCN2A         NaN      NaN       NaN      NaN           Splicesites
4     SCN2A         NaN      NaN       NaN      NaN           Splicesites
..      ...         ...      ...       ...      ...                   ...
191   OPHN1         NaN      NaN       NaN      NaN           Splicesites
192   OPHN1         NaN      NaN       NaN      NaN           Splicesites
193    DLG3         NaN      NaN       NaN      NaN           Splicesites
194    DLG3         NaN      NaN       NaN      NaN           Splicesites
195   NLGN3         NaN      NaN       NaN      NaN           Splicesites

[196 rows x 6 columns]

# Last touches Likely pathogenic

In [39]:
# Join all 4 dataframes and rename index to have correct numbers
df_final_lp = pd.concat([df2_fs_lp, df2_ms_lp, df2_ns_lp, df2_ss_lp])
df_final_lp.index = range(len(df_final_lp))
df_final_lp

     Gene(s) Prot change firstcol secondcol thirdcol Molecular Consequence
0       DVL1      S539fs        S       539       fs            Frameshift
1       DVL1      P531fs        P       531       fs            Frameshift
2       DVL1      P551fs        P       551       fs            Frameshift
3       DVL1      F524fs        F       524       fs            Frameshift
4       DVL1      P521fs        P       521       fs            Frameshift
...      ...         ...      ...       ...      ...                   ...
2018   OPHN1         NaN      NaN       NaN      NaN           Splicesites
2019   OPHN1         NaN      NaN       NaN      NaN           Splicesites
2020    DLG3         NaN      NaN       NaN      NaN           Splicesites
2021    DLG3         NaN      NaN       NaN      NaN           Splicesites
2022   NLGN3         NaN      NaN       NaN      NaN           Splicesites

[2023 rows x 6 columns]

In [40]:
# Add The Clinical Significance
df_final_lp["Clinical Significance"] = 'Likely pathogenic'
df_final_lp

,Gene(s),Prot change,firstcol,secondcol,thirdcol,Molecular Consequence,Clinical Significance
0,DVL1,S539fs,S,539,fs,Frameshift,Likely pathogenic
1,DVL1,P531fs,P,531,fs,Frameshift,Likely pathogenic
2,DVL1,P551fs,P,551,fs,Frameshift,Likely pathogenic
3,DVL1,F524fs,F,524,fs,Frameshift,Likely pathogenic
4,DVL1,P521fs,P,521,fs,Frameshift,Likely pathogenic
...,...,...,...,...,...,...,...
2018,OPHN1,NaN,NaN,NaN,NaN,Splicesites,Likely pathogenic
2019,OPHN1,NaN,NaN,NaN,NaN,Splicesites,Likely pathogenic
2020,DLG3,NaN,NaN,NaN,NaN,Splicesites,Likely pathogenic
2021,DLG3,NaN,NaN,NaN,NaN,Splicesites,Likely pathogenic
2022,NLGN3,NaN,NaN,NaN,NaN,Splicesites,Likely pathogenic

# Last touches General

In [41]:
# Join all 4 dataframes and rename index to have correct numbers
df_final = pd.concat([df_final_p, df_final_lp])
df_final.index = range(len(df_final))
df_final

,Gene(s),Prot change,firstcol,secondcol,thirdcol,Molecular Consequence,Clinical Significance
0,DVL1,S578fs,S,578,fs,Frameshift,Pathogenic
1,DVL1,T565fs,T,565,fs,Frameshift,Pathogenic
2,DVL1,S562fs,S,562,fs,Frameshift,Pathogenic
3,DVL1,S542fs,S,542,fs,Frameshift,Pathogenic
4,DVL1,S564fs,S,564,fs,Frameshift,Pathogenic
...,...,...,...,...,...,...,...
3939,OPHN1,NaN,NaN,NaN,NaN,Splicesites,Likely pathogenic
3940,OPHN1,NaN,NaN,NaN,NaN,Splicesites,Likely pathogenic
3941,DLG3,NaN,NaN,NaN,NaN,Splicesites,Likely pathogenic
3942,DLG3,NaN,NaN,NaN,NaN,Splicesites,Likely pathogenic
3943,NLGN3,NaN,NaN,NaN,NaN,Splicesites,Likely pathogenic

In [42]:
# Add The Database
df_final["Database"] = 'ClinVar'
df_final

,Gene(s),Prot change,firstcol,secondcol,thirdcol,Molecular Consequence,Clinical Significance,Database
0,DVL1,S578fs,S,578,fs,Frameshift,Pathogenic,ClinVar
1,DVL1,T565fs,T,565,fs,Frameshift,Pathogenic,ClinVar
2,DVL1,S562fs,S,562,fs,Frameshift,Pathogenic,ClinVar
3,DVL1,S542fs,S,542,fs,Frameshift,Pathogenic,ClinVar
4,DVL1,S564fs,S,564,fs,Frameshift,Pathogenic,ClinVar
...,...,...,...,...,...,...,...,...
3939,OPHN1,NaN,NaN,NaN,NaN,Splicesites,Likely pathogenic,ClinVar
3940,OPHN1,NaN,NaN,NaN,NaN,Splicesites,Likely pathogenic,ClinVar
3941,DLG3,NaN,NaN,NaN,NaN,Splicesites,Likely pathogenic,ClinVar
3942,DLG3,NaN,NaN,NaN,NaN,Splicesites,Likely pathogenic,ClinVar
3943,NLGN3,NaN,NaN,NaN,NaN,Splicesites,Likely pathogenic,ClinVar

In [43]:
df_final.to_csv('File2(ClinVar).txt', header=True, index=None, sep=' ', mode='a')

In [44]:
# At the end we're going to use this columns in order to join the file with the GnomAD ones in order
# to get the file of counts.
df_final_2 = df_final[["Gene(s)", "Prot change", "Molecular Consequence", "Clinical Significance", "Database"]]
df_final_2.to_csv('File2_tojoinwith_GnomAD(ClinVar).txt', header=True, index=None, sep=' ', mode='a')