In [1]:
import pandas as pd

In [2]:
# This program checks whichs gene names are in both Uniprot and GnomAD files and gives an output (Match(ClinVar).txt) with the hits

In [3]:
df=pd.read_csv('myOutFile_table(Uniprot).txt', delimiter=' ')
df.head()

,ID,Uniprot_code,Gene_name,Pfam_code,Transmembrane_Regions,Unnamed: 5
0,MOT11_HUMAN,Q8NCK7,SLC16A11,PF07690,36..56_78..98_106..126_131..151_163..183_198.....,NaN
1,MOGT3_HUMAN,Q86VF5,MOGAT3,PF03982,29..49_50..70_137..157,NaN
2,MOGS_HUMAN,Q13724,MOGS,PF03200_PF16923,39..59,NaN
3,POPD1_HUMAN,Q8NE79,BVES,PF04831,49..69_71..91_93..113,NaN
4,S1PR1_HUMAN,P21453,S1PR1,PF00001,47..68_83..104_117..138_161..182_197..224_258....,NaN

In [4]:
df2=pd.read_csv('GnomAD_with_GeneNames_nonPatho.txt', delimiter=' ')
df2

            Gene(s) HGVS Consequence
0            TSPAN6      c.*39+29T>C
1            TSPAN6      c.*39+27G>A
2            TSPAN6      c.*39+20C>T
3            TSPAN6       c.*39+4C>A
4            TSPAN6         c.*33C>T
...             ...              ...
3638458  AL138899.3         c.-58T>C
3638459  AL138899.3         c.-61T>A
3638460  AL138899.3         c.-62C>A
3638461  AL138899.3         c.-69C>T
3638462  AL138899.3         c.-70G>T

[3638463 rows x 2 columns]

In [5]:
df2['Hit']=df2['Gene(s)'].isin(df['Gene_name'])
df2.head(50)

   Gene(s)      HGVS Consequence   Hit
0   TSPAN6           c.*39+29T>C  True
1   TSPAN6           c.*39+27G>A  True
2   TSPAN6           c.*39+20C>T  True
3   TSPAN6            c.*39+4C>A  True
4   TSPAN6              c.*33C>T  True
5   TSPAN6              c.*29C>T  True
6   TSPAN6              c.*24C>T  True
7   TSPAN6              c.*12T>C  True
8   TSPAN6               c.*7G>A  True
9   TSPAN6           p.Ter246Ter  True
10  TSPAN6           p.Ile244Ter  True
11  TSPAN6           p.Ile237Thr  True
12  TSPAN6           p.Arg235His  True
13  TSPAN6           p.Arg235Cys  True
14  TSPAN6           p.Cys232Cys  True
15  TSPAN6           p.Ala230Thr  True
16  TSPAN6           p.Leu229Leu  True
17  TSPAN6           p.Leu229Phe  True
18  TSPAN6           c.670-16C>G  True
19  TSPAN6           c.670-19G>T  True
20  TSPAN6           c.670-31G>A  True
21  TSPAN6           c.670-33A>G  True
22  TSPAN6           c.670-39T>A  True
23  TSPAN6           c.670-42C>A  True
24  TSPAN6           c.670-46A>C  True
25  TSPAN6           c.670-58C>T  True
26  TSPAN6           c.670-66A>G  True
27  TSPAN6    c.670-78_670-75del  True
28  TSPAN6  c.669+484_669+487del  True
29  TSPAN6  c.669+478_669+481del  True
30  TSPAN6          c.669+482T>A  True
31  TSPAN6          c.669+469T>C  True
32  TSPAN6          c.669+468G>A  True
33  TSPAN6          c.669+467A>G  True
34  TSPAN6          c.669+463T>C  True
35  TSPAN6          c.669+461G>A  True
36  TSPAN6          c.669+459C>T  True
37  TSPAN6          c.669+458A>C  True
38  TSPAN6          c.669+451C>T  True
39  TSPAN6          c.669+435G>A  True
40  TSPAN6          c.669+434C>T  True
41  TSPAN6          c.669+430A>C  True
42  TSPAN6           p.Asp136Tyr  True
43  TSPAN6            c.406-5G>T  True
44  TSPAN6          c.669+407G>A  True
45  TSPAN6          c.669+394del  True
46  TSPAN6          c.669+387A>C  True
47  TSPAN6          c.669+385T>G  True
48  TSPAN6          c.669+384A>G  True
49  TSPAN6          c.669+380G>A  True

In [6]:
df2.to_csv(r'Fitxer_intermig_2', header=True, index=None, sep=' ', mode='w')

In [7]:
f1=open("Fitxer_intermig_2","r")
u=f1.readlines()
f1.close()
#print(u)
p=[]
header=('Gene(s) HGVSConsequence\n')
p.append(header)
for e in u:
    try:
        x=e.split()
        #print(x)
        if x[2]=='True':
            p.append(e.replace('True',''))
    except IndexError:
         pass
print(p)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [8]:
outF = open("Match(GnomAD)_nonPatho.txt", "w")
for line in p:
  # write line to output file
  outF.write(line)
  # outF.write("\n") --> si volgues separar lina per linia afegiria aixÃ²
outF.close()